### PR TITLE
Upgrade to Stylus 0.54

### PR DESCRIPTION
**Pull request by thybzi**

### CODE REVIEW

**Comment by thybzi** [comment]
Hey, that was perfectly quick :-D

**Comment by vladikoff** [comment]
:)

**Comment by vladikoff** [comment]
Hm thought it was green, any idea what happened to this option:

```
Running "nodeunit:tests" (nodeunit) task
Testing stylus_test.js....F.........
>> stylus - embedurl
>> Message: `embedurlOpts` limit should prevent Data URI embed
>> Error: '.normal{background-image:url("test.png")}.base64not{background-image:url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAATUlEQVQYV5WQAQoAIAgD7f+PrhZM5ioiQSS81laLiD77Wc1AnFlFQEGFNpigToVSyEFA/sqycFLyYAXkJUws6DcDfYdxG1S9KipQ/ngAy3ccAe3ha2EAAAAASUVORK5CYII=")}' == '.normal{background-image:url("test.png")}.base64not{background-image:url("test.png")}'
>> at Object.exports.stylus.embedurl (test/stylus_test.js:69:10)
``` 

?

**Comment by vladikoff** [comment]
cc @thybzi

**Comment by thybzi** [comment]
Strange thing, I'll try to investigate

**Comment by thybzi** [comment]
For now, seems that `limit` option set value is somehow overridden to `false`.
Continuing investigation.

**Comment by thybzi** [comment]
Gotcha! Here is it:
https://github.com/stylus/stylus/commit/fb296c59f4639733e654317d4426807418e6b83f#diff-2484967dbaf30d736500a330414ff5d1R220

Now trying to find out why that `false` value was ever needed here, and how to avoid it

**Comment by vladikoff** [comment]
Oh Snap! :snake:

**Comment by thybzi** [comment]
Now I'm sure that it's just naming conflict with their new bif called `embedurl`
I think we should rename our tests function having the same name.
Should it be `embedurllimit` or whatever?

**Comment by vladikoff** [comment]
@thybzi sure, sounds good!

**Comment by thybzi** [comment]
@vladikoff No, my bad. This function name is used not only in "size-limited" cases.
Preparing pull request with rename `embedurl` (defined in grunt-contrib-stylus) it to `data-uri()`.

**Comment by thybzi** [comment]
Fixed here https://github.com/gruntjs/grunt-contrib-stylus/pull/151
Please accept, and we would be able to upgrade to stylus 0.54.0

**Pull request merged**
