### PR TITLE
added sourcemap support

### PR DESCRIPTION
**Pull request by pixeldrew**

### CODE REVIEW

**Comment by sapegin** [comment]
Any news here?

**Comment by kylechadha** [comment]
Also interested in an update here. Thanks!

**Comment by argyleink** [comment]
that PR looks like what I would have attempted. what can we do to help this move forward?

**Comment by sindresorhus** [comment]
@argyleink Submit a new PR that fixes the current issues.

**Comment by Enideo** [comment]
I got sourcemaps working without a pull request, see my comment at https://github.com/gruntjs/grunt-contrib-stylus/issues/118#issuecomment-98126180

**Comment by pixeldrew** [comment]
Sourcemaps were never a problem with inline, it has always worked. When using a path reference it doesn't work due to the way this plugin builds the stylus files.

**Comment by vladikoff** [comment]
Feel free to use this fork, if anyone else needs this PR please reopen a new one.  Thanks!

**Pull request closed without merging**
